group=com.legitimoose.legitslimepaper
version=1.21.6-R0.1-SNAPSHOT
mcVersion=1.21.6

#Update with ASP!! (also update gradle/libs.versions.toml)
aspRef=856778c5224baf826aeee8cc8f8f9f3c7a446715
apiVersion=4.1.0-SNAPSHOT

org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false

org.gradle.jvmargs=-Xmx10G
